import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { Poppins } from 'next/font/google'
const poppins = Poppins({
  subsets:['latin'],
  weight: ['100', '200', '300', '400', '500','600', '700', '800','900'],
  variable:'--font-poppins'
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Daily My shopping',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
